### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION

### ISSUE THREAD

**Issue by wpinfotech** [hzitoun/android-camera2-secret-picture-taker#7]
AndroidRuntime: FATAL EXCEPTION: Thread-1116
                                                                                    java.lang.IllegalArgumentException: Surface had no valid native Surface.
                                                                                        at android.hardware.camera2.legacy.LegacyCameraDevice.nativeGetSurfaceId(Native Method)
                                                                                        at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceId(LegacyCameraDevice.java:658)
                                                                                        at android.hardware.camera2.legacy.LegacyCameraDevice.containsSurfaceId(LegacyCameraDevice.java:678)
                                                                                        at android.hardware.camera2.legacy.RequestThreadManager$2.onPictureTaken(RequestThreadManager.java:220)
                                                                                        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1248)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                        at android.os.Looper.loop(Looper.java:207)
                                                                                        at android.hardware.camera2.legacy.CameraDeviceUserShim$CameraLooper.run(CameraDeviceUserShim.java:136)
                                                                                        at java.lang.Thread.run(Thread.java:818)

**Comment by hzitoun** [comment]
Please explain how you got this issue and the steps to reproduce it.
